### ISSUE TITLE
Lot of errors

### ISSUE THREAD

**Issue by Bkoech** [ringkubd/jobportal#1]
QueryExceptionSQLSTATE[HY000]: General error: 2031 (SQL: select `name`, `id` from `divisions` where `country_id` = ?)
--
in Connection.php (line 647)
at Connection->runQueryCallback('select `name`, `id` from `divisions` where `country_id` = ?', array(), object(Closure))in Connection.php (line 607)
at Connection->run('select `name`, `id` from `divisions` where `country_id` = ?', array(), object(Closure))in Connection.php (line 326)
at Connection->select('select `name`, `id` from `divisions` where `country_id` = ?', array(), true)in Builder.php (line 1710)
at Builder->runSelect()in Builder.php (line 1695)
at Builder->get(array('name', 'id'))in Builder.php (line 1893)
at Builder->pluck('name', 'id')in PublicController.php (line 139)
at PublicController->get_division()in PublicController.php (line 24)
at PublicController->index()
at call_user_func_array(array(object(PublicController), 'index'), array())in Controller.php (line 55)
at Controller->callAction('index', array())in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(PublicController), 'index')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 574)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in UsersOnline.php (line 19)
at UsersOnline->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)
at require_once('C:\\wamp64\\www\\jobportal\\public\\index.php')in server.php (line 21)

**Comment by ringkubd** [comment]
Sorry..  we didn't use migration for all table that's for you got error.
you check it here www.webexpart.website/idbjobportal/public. After review
that if you really want to use this project just email me I will send you
all required file.. thank you.

**Comment by CareerIntelligenceHCD** [comment]
You really have a good work here, I wish you had a tutorial series on youtube. It would have been great. How do i get your email ? for the remaining required file ? My email is papasunnee@gmail.com

**Comment by ringkubd** [comment]
hey,
i have just upload database backup file.. i hope now you can use it ...
Thank you..
